name: Deployment

concurrency: production

on:
    push:
        branches:
            - main

jobs:
    deployment:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Search website location
              run: 'cd /var/www/html'

            - name: Deploy
              with:
                script: './deploy.sh'
